//! `profiles/<profile>/modlist.txt`.
//!
//! MO2 stores the list in *reverse* priority order: the first line is the
//! mod that wins conflicts. [`ModList`] keeps entries in MO2's UI order
//! (lowest priority first) and flips on read/write.

use std::path::Path;

use crate::{Error, Result};

const HEADER: &str = "# This file was automatically generated by Mod Organizer.";
const SEPARATOR_SUFFIX: &str = "_separator";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EntryState {
    /// `+name`
    Enabled,
    /// `-name`
    Disabled,
    /// `*name` — an entry MO2 doesn't manage (game DLC, foreign files).
    Unmanaged,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Entry {
    /// Folder name under `mods/`.
    pub name: String,
    pub state: EntryState,
}

impl Entry {
    pub fn enabled(name: impl Into<String>) -> Self {
        Self { name: name.into(), state: EntryState::Enabled }
    }

    pub fn disabled(name: impl Into<String>) -> Self {
        Self { name: name.into(), state: EntryState::Disabled }
    }

    /// MO2 separators are empty mod folders named `<title>_separator`.
    pub fn separator(title: &str) -> Self {
        Self::disabled(format!("{title}{SEPARATOR_SUFFIX}"))
    }

    pub fn is_separator(&self) -> bool {
        self.name.ends_with(SEPARATOR_SUFFIX)
    }

    pub fn separator_title(&self) -> Option<&str> {
        self.name.strip_suffix(SEPARATOR_SUFFIX)
    }
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ModList {
    /// Lowest priority first, as in MO2's left pane.
    pub entries: Vec<Entry>,
}

impl ModList {
    pub fn parse(text: &str, path: &Path) -> Result<Self> {
        let mut entries = Vec::new();
        for (idx, raw) in text.lines().enumerate() {
            let line = raw.trim_end_matches('\r');
            if line.trim().is_empty() || line.starts_with('#') {
                continue;
            }
            let mut chars = line.chars();
            let state = match chars.next() {
                Some('+') => EntryState::Enabled,
                Some('-') => EntryState::Disabled,
                Some('*') => EntryState::Unmanaged,
                _ => {
                    return Err(Error::Parse {
                        path: path.to_owned(),
                        message: format!("line {}: expected +, - or * prefix: {line:?}", idx + 1),
                    })
                }
            };
            entries.push(Entry { name: chars.as_str().to_owned(), state });
        }
        entries.reverse();
        Ok(Self { entries })
    }

    pub fn load(path: &Path) -> Result<Self> {
        let text = std::fs::read_to_string(path).map_err(|e| Error::io(path, e))?;
        Self::parse(&text, path)
    }

    pub fn render(&self) -> String {
        let mut out = String::from(HEADER);
        out.push_str("\r\n");
        for e in self.entries.iter().rev() {
            out.push(match e.state {
                EntryState::Enabled => '+',
                EntryState::Disabled => '-',
                EntryState::Unmanaged => '*',
            });
            out.push_str(&e.name);
            out.push_str("\r\n");
        }
        out
    }

    /// Writes via a temp file + rename so MO2 never sees a half-written list.
    pub fn save(&self, path: &Path) -> Result<()> {
        let tmp = path.with_extension("txt.lyno-tmp");
        std::fs::write(&tmp, self.render()).map_err(|e| Error::io(&tmp, e))?;
        std::fs::rename(&tmp, path).map_err(|e| Error::io(path, e))
    }

    pub fn get(&self, name: &str) -> Option<&Entry> {
        self.entries.iter().find(|e| e.name == name)
    }

    /// Mods only (no separators, no unmanaged entries).
    pub fn mods(&self) -> impl Iterator<Item = &Entry> {
        self.entries
            .iter()
            .filter(|e| e.state != EntryState::Unmanaged && !e.is_separator())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "# This file was automatically generated by Mod Organizer.\r\n\
        +Highest\r\n\
        -Disabled Mod\r\n\
        -Core_separator\r\n\
        +Lowest\r\n\
        *DLC: Phantom Liberty\r\n";

    #[test]
    fn parses_in_ui_order() {
        let list = ModList::parse(SAMPLE, Path::new("modlist.txt")).unwrap();
        let names: Vec<_> = list.entries.iter().map(|e| e.name.as_str()).collect();
        assert_eq!(names, ["DLC: Phantom Liberty", "Lowest", "Core_separator", "Disabled Mod", "Highest"]);
        assert_eq!(list.get("Disabled Mod").unwrap().state, EntryState::Disabled);
        assert_eq!(list.get("Core_separator").unwrap().separator_title(), Some("Core"));
        assert_eq!(list.mods().count(), 3);
    }

    #[test]
    fn roundtrips() {
        let list = ModList::parse(SAMPLE, Path::new("modlist.txt")).unwrap();
        assert_eq!(list.render(), SAMPLE);
    }

    #[test]
    fn rejects_garbage() {
        assert!(ModList::parse("oops\n", Path::new("modlist.txt")).is_err());
    }

    #[test]
    fn save_is_atomic_and_readable() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("modlist.txt");
        let list = ModList { entries: vec![Entry::separator("Base"), Entry::enabled("A")] };
        list.save(&p).unwrap();
        assert_eq!(ModList::load(&p).unwrap(), list);
        assert!(!dir.path().join("modlist.txt.lyno-tmp").exists());
    }
}
